version: "3"
services:
  problem-solving-c:
    image: gcc:latest
    container_name: language-c
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./c:/home"

  problem-solving-cpp:
    image: gcc:latest
    container_name: language-cpp
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./c++:/home"

  problem-solving-java:
    image: openjdk:11
    container_name: language-java
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./java:/home"

  problem-solving-python:
    image: python:latest
    container_name: language-python
    working_dir: /home
    stdin_open: true
    tty: true
    volumes:
      - "./python:/home"